web:
  build: .
  ports:
   - "3000:3000"
  links:
   - mysql
   - rabbitmq
  environment:
   - DATABASE_URL=mysql://root:wtpass@mysql:3306/wt_dev
   - STRIPE_PRIVATE_KEY=sk_test_EmjKDhDj01gLiLl5krTWsr13
   - STRIPE_PUBLIC_KEY=pk_test_0mBt8qMYWhuTNKEdcf9kG3Gm
   - SENGRID_USERNAME=sarcilav
   - SENGRID_KEY="P@wU8Z#wGHAZ^n"
   - REDIS_URI=redis://redis:6379

consumer:
  build: ./consumers
  links:
   - cassandra_seed
   - rabbitmq
  environment:
   - CASS_KEYSPACE=developer
   - CASS_REPLICA_FACTOR=1
   - CASSANDRA_1_PORT=cassandra_seed
   - TITAN_1_PORT=cassandra_seed
   - RABBITMQ_1_PORT=rabbitmq
   
pre-launch:
  build: ./pre-launch/
  ports:
   - "5000:3000"
  links:
   - rabbitmq
   - mysql
   - redis
  environment:
   - RABBITMQ_1_PORT=rabbitmq
   - DATABASE_URL=mysql://root:wtpass@mysql:3306/wt_dev
   - STRIPE_PRIVATE_KEY=sk_test_EmjKDhDj01gLiLl5krTWsr13
   - STRIPE_PUBLIC_KEY=pk_test_0mBt8qMYWhuTNKEdcf9kG3Gm
   - SENGRID_USERNAME=sarcilav
   - SENGRID_KEY="P@wU8Z#wGHAZ^n"
   - REDIS_URI=redis://redis:6379
   - WT_URL=webtalk.co:5000

redis:
  image: redis
  ports:
    - "6379:6379"

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=wt_dev
    - MYSQL_ROOT_PASSWORD=wtpass
  
cassandra_seed:
  image: spotify/cassandra
  ports:
    - "9160:9160"
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"

rabbitmq:
  ports:
    - "5672:5672"
    - "8080:8080"
    - "15672:15672"
    - "25672:25672"
    - "4369:4369"
    - "5671:5671"
  image: rabbitmq:management