web:
  #memory: 1024MB
  build: .
  ports:
   - "5000:3000"
  volumes:
   - .:/app
  links:
   - cassandra
   - elasticsearch
   - rabbitmq
   - cassandra_2

consumer:
  #memory: 1024MB
  image: clojure
  ports:
    - "5672:5672"
  links:
    - rabbitmq

cassandra:
  image: cassandra
  #memory: 4096MB

cassandra_2:
  image: cassandra
  links:
   - cassandra
  environment:
   - CASSANDRA_SEEDS=CASSANDRA_PORT_7000_TCP_ADDR
  

elasticsearch:
  image: elasticsearch
  #memory: 4096MB

rabbitmq:
  image: rabbitmq
  #memory: 8192MB