# web:
#   cpu_shares: 100
#   memory: 1024MB
#   build: .
#   ports:
#    - "5000:3000"
#   volumes:
#    - .:/app
#   links:
#    - cassandra_seed
#    - elasticsearch
#    - rabbitmq
#    - cassandra_non_seed
#   environment:
#    - CASS_KEYSPACE=develop
#    - CASS_REPLICA_FACTOR=1

consumer:
  cpu_shares: 100
  mem_limit: 1024000000
  build: ./consumers/
  ports:
    - "5672:5672"
  volumes:
   - ./consumers/:/consumer
  links:
   - cassandra_seed
   - elasticsearch
   - rabbitmq
   - cassandra_non_seed
  environment:
   - CASS_KEYSPACE=develop
   - CASS_REPLICA_FACTOR=1
   - 

cassandra_seed:
  cpu_shares: 100
  image: cassandra
  mem_limit: 4096000000

cassandra_non_seed:
  cpu_shares: 100
  mem_limit: 4096000000
  image: cassandra
  links:
   - cassandra_seed
  environment:
   - CASSANDRA_SEEDS=cassandra_seed
  

elasticsearch:
  cpu_shares: 100
  image: elasticsearch
  mem_limit: 4096000000

rabbitmq:
  cpu_shares: 100
  ports:
    - "15672:15672"
  image: rabbitmq
  mem_limit: 8192000000