web:
  #memory: 1024MB
  build: .
  ports:
   - "5000:3000"
  volumes:
   - .:/app
  links:
   - cassandra_seed
   - elasticsearch
   - rabbitmq
   - cassandra_non_seed
  environment:
   - CASS_KEYSPACE=develop
   - CASS_REPLICA_FACTOR=1

consumer:
  #memory: 1024MB
  image: clojure
  ports:
    - "5672:5672"
  links:
    - rabbitmq

cassandra_seed:
  image: cassandra
  #memory: 4096MB

cassandra_non_seed:
  image: cassandra
  links:
   - cassandra_seed
  environment:
   - CASSANDRA_SEEDS=cassandra_seed
  

elasticsearch:
  image: elasticsearch
  #memory: 4096MB

rabbitmq:
  image: rabbitmq
  #memory: 8192MB