CREATE TABLE users
(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 stripe_account_id INT,
 name VARCHAR(250),
 email VARCHAR(50) UNIQUE,
 birthday DATE,
 titan_id INT,
 profession VARCHAR(100),
 avatar_url VARCHAR(250),
 type VARCHAR(100),
 city_name VARCHAR(100),
 job_title VARCHAR(50),
 former_job_title VARCHAR(50),
 place_of_employment VARCHAR(100),
 former_place_of_employment VARCHAR(100),
 start_date DATE,
 end_date DATE,
 location VARCHAR (250),
 ocupation VARCHAR(100),
 industry VARCHAR(100),
 seeking_job BOOLEAN,
 phone VARCHAR(20),
 degree VARCHAR(100),
 field_of_study VARCHAR(100),
 school_name VARCHAR(100),
 facebook_profile VARCHAR(200),
 linkedin_profile VARCHAR(200),
 gender VARCHAR(50),
 admin BOOLEAN,
 last_login TIME,
 is_active BOOLEAN,
 password VARCHAR(100),
 FOREIGN KEY (stripe_account_id) REFERENCES customer_stripe_accounts(id)
);

